# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bottler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Distillery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wb_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('founded', models.CharField(blank=True, default='', max_length=255)),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('capacity_per_year', models.CharField(blank=True, default='', max_length=255)),
                ('website', models.CharField(blank=True, default='', max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('closed', models.CharField(blank=True, default='', max_length=255)),
                ('spirit_stills', models.IntegerField(default=0)),
                ('wash_stills', models.IntegerField(default=0)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Whisky',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('wb_url', models.CharField(max_length=255)),
                ('wb_id', models.IntegerField()),
                ('age', models.CharField(blank=True, max_length=255)),
                ('size', models.IntegerField(default=0)),
                ('strength', models.FloatField(default=0)),
                ('barcode', models.CharField(blank=True, max_length=255)),
                ('vintage', models.CharField(blank=True, max_length=255)),
                ('bottling_series', models.CharField(max_length=255)),
                ('cask_number', models.CharField(max_length=255)),
                ('bottler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Bottler')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Brand')),
                ('cask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Cask')),
                ('distillery', models.ManyToManyField(to='api.Distillery')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Type')),
            ],
        ),
    ]
